import { mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, readdirSync, lstatSync, mkdtempSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { loadPage, assertPair } from './content.ts';
import { copyDiagrams, diagramMetadata, generateDiagrams } from './diagrams.ts';
import { basePath, renderPage, home, sessionsIndex, projectsIndex } from './render.ts';
import { renderPortfolio } from '../../apps/portfolio/src/portfolio.ts';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const output=resolve(root,'dist');
const base=basePath(process.env.BASE_PATH);
// Validate all inputs before touching output. Only explicit public files are read.
const routes=['sessions/PA-S001','projects/portfolio','projects/p0','projects/engineering-book'];
const pairs=routes.map(route=>({route,es:loadPage(resolve(root,`site/es/${route}/page.json`)),en:loadPage(resolve(root,`site/en/${route}/page.json`))}));
for (const p of pairs) assertPair(p.es,p.en);
const sessionPair=pairs.find(pair=>pair.route==='sessions/PA-S001');
if (!sessionPair) throw new Error('PA-S001 session source is missing');
const pages=pairs.flatMap(pair=>[pair.es,pair.en]);
const progress=readFileSync(resolve(root,'project-sources/07-PROGRESS.md'),'utf8');
const status=progress.match(/Current overall status:\s*(Not started|Partial|Completed|Revisit)/)?.[1];
if (!status) throw new Error('Cannot read canonical status from 07-PROGRESS.md');
const systemsStatus=progress.match(/Engineering Book \/ Portfolio:\s*(Not started|Partial|Completed|Revisit)/)?.[1];
if (!systemsStatus) throw new Error('Cannot read P0 systems status from 07-PROGRESS.md');
const mastery: unknown=JSON.parse(readFileSync(resolve(root,'data/mastery/PA-S001.json'),'utf8'));
if (typeof mastery !== 'object' || mastery === null || !('status' in mastery) || typeof mastery.status !== 'string') throw new Error('Invalid mastery source');
const generatedRoot=mkdtempSync(resolve(tmpdir(),'pa-s001-diagrams-'));
try {
const generatedDiagrams=generateDiagrams(root,diagramMetadata(pages),generatedRoot);
const marker=resolve(output,'.pa-generated');
if (existsSync(output)) {
  if (lstatSync(output).isSymbolicLink()) throw new Error('Refusing symlink dist');
  if (readdirSync(output).length && !existsSync(marker)) throw new Error('Refusing to replace unmanaged dist');
  rmSync(output,{recursive:true});
}
function emit(relative: string, value: string): void {
  const path=resolve(output,relative); mkdirSync(dirname(path),{recursive:true}); writeFileSync(path,value);
}
emit('.pa-generated','Generated by PA-S001; do not store source files here.\n');
emit('assets/site.css',readFileSync(resolve(root,'site/tooling/site.css'),'utf8'));
emit('assets/study.js',readFileSync(resolve(root,'site/shared/assets/study.js'),'utf8'));
copyDiagrams(generatedRoot,output,generatedDiagrams,pages);
emit('.nojekyll','');
emit('index.html',home('es',base,sessionPair.es,status,mastery.status,systemsStatus));
emit('portfolio/index.html',renderPortfolio(base));
for (const lang of ['es','en'] as const) {
  emit(`${lang}/index.html`,home(lang,base,sessionPair[lang],status,mastery.status,systemsStatus));
  emit(`${lang}/sessions/index.html`,sessionsIndex(lang,base));
  emit(`${lang}/projects/index.html`,projectsIndex(lang,base));
  for (const p of pairs) emit(`${lang}/${p.route}/index.html`,renderPage(p[lang],base,p.route));
}
console.log(`Built ${8 + pages.length} HTML pages and ${generatedDiagrams.length} SVG diagram source(s) in ${output}; BASE_PATH=${base}; mastery=${mastery.status}.`);
} finally { rmSync(generatedRoot,{recursive:true,force:true}); }
