import { mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, readdirSync, lstatSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadPage, assertPair } from './content.ts';
import { basePath, renderPage, home, sessionsIndex, projectsIndex } from './render.ts';
import { renderPortfolio } from '../../portfolio/src/portfolio.ts';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../../..');
const output=resolve(root,'dist');
const base=basePath(process.env.BASE_PATH);
// Validate all inputs before touching output. Only explicit public files are read.
const routes=['sessions/PA-S001','projects/p0','projects/engineering-book'];
const pairs=routes.map(route=>({route,es:loadPage(resolve(root,`site/es/${route}/page.json`)),en:loadPage(resolve(root,`site/en/${route}/page.json`))}));
for (const p of pairs) assertPair(p.es,p.en);
const marker=resolve(output,'.pa-generated');
if (existsSync(output)) {
  if (lstatSync(output).isSymbolicLink()) throw new Error('Refusing symlink dist');
  if (readdirSync(output).length && !existsSync(marker)) throw new Error('Refusing to replace unmanaged dist');
  rmSync(output,{recursive:true});
}
function emit(relative: string, value: string): void {
  const path=resolve(output,relative); mkdirSync(dirname(path),{recursive:true}); writeFileSync(path,value);
}
emit('.pa-generated','Generated by PA-S001; do not store source files here.\n');
emit('assets/book.css',readFileSync(resolve(root,'apps/book/src/book.css'),'utf8'));
emit('.nojekyll','');
emit('index.html',home('es',base));
emit('portfolio/index.html',renderPortfolio(base));
for (const lang of ['es','en'] as const) {
  emit(`${lang}/index.html`,home(lang,base));
  emit(`${lang}/sessions/index.html`,sessionsIndex(lang,base));
  emit(`${lang}/projects/index.html`,projectsIndex(lang,base));
  for (const p of pairs) emit(`${lang}/${p.route}/index.html`,renderPage(p[lang],base));
}
console.log(`Built 14 HTML pages in ${output}; BASE_PATH=${base}. No mastery assessed.`);
